language: java

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
#         - brew install gnu-sed
      
# install:
#   - if [[ ${TRAVIS_OS_NAME} = 'osx' ]]; then export SED="/usr/local/bin/gsed"; fi;

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
    
script:
  - asdf plugin-add sbt https://github.com/nverno/asdf-sbt
  - asdf list-all sbt
  - LATEST_VERSION=$(asdf list-all sbt | tail -1)
  - asdf install sbt $LATEST_VERSION
  - asdf global sbt $LATEST_VERSION
  - asdf current sbt
  - test $(asdf current sbt | cut -d ' ' -f1) = $LATEST_VERSION
  - asdf plugin-test sbt https://github.com/nverno/asdf-sbt.git
